Repository bcgov/vue-shared-components, pull requests merged in 2020-09, with the labels that each got.

#13 Add table and table element components with stories
  src/components/table/Table.css
  src/components/table/Table.stories.js
  src/components/table/Table.stories.mdx
  src/components/table/Table.vue
  src/components/table/TableElement.vue
  src/modules/tableTestData.js
Labels: enhancement

#17 Add more states to display box
  src/components/display-box/DisplayBox.stories.js
  src/components/display-box/DisplayBox.stories.mdx
  src/components/display-box/DisplayBox.vue
Labels: enhancement

#18 Alert component and DisplayBox component fixed using slots
  src/components/alert/Alert.css
  src/components/alert/Alert.stories.js
  src/components/alert/Alert.stories.mdx
  src/components/alert/Alert.vue
  src/components/alert/GenerateIcon.vue
  src/components/display-box/DisplayBox.stories.js
  src/components/display-box/DisplayBox.vue
Labels: enhancement

#19 Add input field component and stories
  src/components/input/Input.css
  src/components/input/Input.stories.js
  src/components/input/Input.stories.mdx
  src/components/input/Input.vue
Labels: enhancement

#21 Create dependabot.yml
  .github/dependabot.yml
Labels: enhancement

#22 Update Dependabot Time
  .github/dependabot.yml
Labels: Git Action

#30 Update README with Getting Started
  README.md
Labels: documentation

#31 Add jest to project and initial footer snapshot test(s)
  package.json
  src/AssetsTransformer.js
  src/components/footer/Footer.test.js
  src/components/footer/__snapshots__/Footer.test.js.snap
  yarn.lock
Labels: enhancement

#32 Jesting, codecov and code climate
  .github/workflows/code-climate-test-coverage.yaml
  package.json
  src/components/table/Table.vue
  src/components/table/TableElement.vue
  yarn.lock
Labels: Git Action, enhancement

#33 add badges for code climate to readme
  README.md
Labels: documentation

#34 Add testing library and alert tests
  package.json
  src/components/alert/Alert.test.js
  src/components/alert/Alert.vue
  src/components/alert/GenerateIcon.vue
  src/components/alert/__snapshots__/Alert.test.js.snap
  src/components/display-box/DisplayBox.vue
  yarn.lock
Labels: enhancement

#35 add callout & loader & sidecard tests and snaps
  src/components/callout/Callout.test.js
  src/components/callout/__snapshots__/Callout.test.js.snap
  src/components/loader/Loader.test.js
  src/components/loader/__snapshots__/Loader.test.js.snap
  src/components/sidecard/Sidecard.test.js
  src/components/sidecard/__snapshots__/Sidecard.test.js.snap
Labels: enhancement

#36 add tou test and snaps
  src/components/terms-of-use/TermsOfUse.test.js
  src/components/terms-of-use/__snapshots__/TermsOfUse.test.js.snap
Labels: enhancement

#38 dont test modules cause they are test data
  package.json
Labels: enhancement

#39 add button & radio & dropdown test and snaps
  src/components/button/Button.test.js
  src/components/button/Button.vue
  src/components/button/__snapshots__/Button.test.js.snap
  src/components/dropdown/Dropdown.test.js
  src/components/dropdown/__snapshots__/Dropdown.test.js.snap
  src/components/radio/Radio.test.js
  src/components/radio/__snapshots__/Radio.test.js.snap
Labels: enhancement

#40 add input test and snaps
  src/components/input/Input.test.js
  src/components/input/__snapshots__/Input.test.js.snap
Labels: enhancement

#41 add table tests, small modifications to props
  src/components/table/Table.test.js
  src/components/table/Table.vue
  src/components/table/TableElement.vue
  src/components/table/__snapshots__/Table.test.js.snap
Labels: enhancement

#42 add creating a release section
  README.md
Labels: documentation, enhancement

#43 Updated Footer to use `ul` instead of `div`, and fixed link URL.
  package.json
  src/components/footer/Footer.vue
  src/components/footer/LinkElement.vue
  src/components/footer/__snapshots__/Footer.test.js.snap
Labels: bug, enhancement

#46 Deploy storybook to github pages
  .github/workflows/deploy-storybook.yml
  package.json
  yarn.lock
Labels: Git Action, enhancement

#47 add missing script
  package.json
Labels: bug

#54 🤖 Transformers, dependabots in disguise
  package.json
  yarn.lock
Labels: dependencies, enhancement
